nodeLinker: node-modules

packageExtensions:
  react@*:
    peerDependencies:
      '@types/react': '*'
  react-dom@*:
    peerDependencies:
      '@types/react': '*'

pnpFallbackMode: all

pnpMode: loose

enableGlobalCache: true

nmMode: hardlinks-local
